name: Push to ECR

on: 
  push:
    branches:
      - featureA

env:
  AWS_REGION: us-east-1

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest


    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@13d241b293754004c80624b5567555c4a39ffbe3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Build, tag, and push image to Amazon ECR
        run: |
          docker build -t my-app: .
          docker tag my-app:1.0 527243421994.dkr.ecr.us-east-1.amazonaws.com/my-app:1.0
          docker push 527243421994.dkr.ecr.us-east-1.amazonaws.com/my-app:1.0


        
    